Repository AY2021S2-CS2103T-W14-4/tp, pull requests merged in 2021-03, with the labels that each got.

#64 Fix Status class and test cases
  src/main/java/seedu/taskify/logic/parser/AddCommandParser.java
  src/main/java/seedu/taskify/model/task/Status.java
  src/main/java/seedu/taskify/storage/JsonAdaptedTask.java
  src/test/data/JsonSerializableTaskifyParserTest/duplicateTaskTaskify.json
  src/test/data/JsonSerializableTaskifyParserTest/typicalTasksTaskify.json
  src/test/java/seedu/taskify/testutil/TypicalTasks.java
Labels: bug

#66 View task by date
  build.gradle
  src/main/java/seedu/taskify/logic/commands/FindCommand.java
  src/main/java/seedu/taskify/logic/commands/TagSearchCommand.java
  src/main/java/seedu/taskify/logic/commands/ViewCommand.java
  src/main/java/seedu/taskify/logic/parser/FindCommandParser.java
  src/main/java/seedu/taskify/logic/parser/TagSearchCommandParser.java
  src/main/java/seedu/taskify/logic/parser/TaskifyParser.java
  src/main/java/seedu/taskify/logic/parser/ViewCommandParser.java
  src/main/java/seedu/taskify/model/task/Date.java
  src/main/java/seedu/taskify/model/task/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/taskify/model/task/predicates/TagContainsKeywordsPredicate.java
  src/main/java/seedu/taskify/model/task/predicates/TaskHasSameDatePredicate.java
  src/test/java/seedu/taskify/logic/commands/CommandTestUtil.java
  src/test/java/seedu/taskify/logic/commands/FindCommandTest.java
  src/test/java/seedu/taskify/logic/commands/TagSearchCommandTest.java
  src/test/java/seedu/taskify/logic/commands/ViewCommandTest.java
  src/test/java/seedu/taskify/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/taskify/logic/parser/TagSearchCommandParserTest.java
  src/test/java/seedu/taskify/logic/parser/TaskifyParserTest.java
  src/test/java/seedu/taskify/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/taskify/model/ModelManagerTest.java
  src/test/java/seedu/taskify/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/taskify/model/task/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/taskify/model/task/predicates/TaskHasSameDatePredicateTest.java
Labels: enhancement, priority.HIGH

#88 Updated links and AB3 references in index.md
  docs/index.md
Labels: type.documentation
